export class ActionSchedule {
  public id: number
  public name: string
  public title: string
  public recipient: string
  public limit_to: boolean
  public entity_value: string
  public entity_status: string
  public start_action_offset: number
  public start_action_unit: string
  public start_action_condition: string
  public start_action_date: string
  public is_repeat: boolean
  public repetition_frequency_unit: string
  public repetition_frequency_interval: number
  public end_frequency_unit: string
  public end_frequency_interval: number
  public end_action: string
  public end_date: string
  public is_active: boolean
  public recipient_manual: string
  public recipient_listing: string
  public body_text: string
  public body_html: string
  public sms_body_text: string
  public subject: string
  public record_activity: boolean
  public mapping_id: string
  public group_id: number
  public msg_template_id: number
  public sms_template_id: number
  public absolute_date: Date
  public from_name: string
  public from_email: string
  public mode: string
  public sms_provider_id: number
  public used_for: string
  public filter_contact_language: string
  public communication_language: string
}
