export class Activity {
  public source_record_id: number
  public activity_type_id: number
  public subject: string
  public activity_date_time: Date
  public duration: number
  public location: string
  public phone_id: number
  public phone_number: string
  public details: string
  public status_id: number
  public priority_id: number
  public parent_id: number
  public is_test: boolean
  public medium_id: number
  public is_auto: boolean
  public relationship_id: number
  public is_current_revision: boolean
  public original_id: number
  public result: string
  public is_deleted: boolean
  public campaign_id: number
  public engagement_level: number
  public weight: number
  public is_star: boolean
  public created_date: Date
  public modified_date: Date
  public custom_12: number
  public custom_7: number
  public custom_9: number
  public custom_8: string
  public custom_10: number
  public id: number
  public tag_id: number
  public file_id: number
  public case_id: number
  public contact_id: number
  public target_contact_id: number
  public source_contact_id: number
  public assignee_contact_id: number
  public is_overdue: boolean
}
