export class Address {
  public id: number
  public contact_id: number
  public location_type_id: number
  public is_primary: boolean
  public is_billing: boolean
  public street_address: string
  public street_number: number
  public street_number_suffix: string
  public street_number_predirectional: string
  public street_name: string
  public street_type: string
  public street_number_postdirectional: string
  public street_unit: string
  public supplemental_address_1: string
  public supplemental_address_2: string
  public supplemental_address_3: string
  public city: string
  public county_id: number
  public state_province_id: number
  public postal_code_suffix: string
  public postal_code: string
  public usps_adc: string
  public country_id: number
  public geo_code_1: number
  public geo_code_2: number
  public manual_geo_code: boolean
  public timezone: string
  public name: string
  public master_id: number
  public world_region: string
}
