export class Contact {
  public id: number
  public contact_type: string
  public contact_sub_type: string
  public do_not_email: boolean
  public do_not_phone: boolean
  public do_not_mail: boolean
  public do_not_sms: boolean
  public do_not_trade: boolean
  public is_opt_out: boolean
  public legal_identifier: string
  public external_identifier: string
  public sort_name: string
  public display_name: string
  public nick_name: string
  public legal_name: string
  public image_URL: string
  public preferred_communication_method: string
  public preferred_language: string
  public preferred_mail_format: string
  public hash: string
  public api_key: string
  public source: string
  public first_name: string
  public middle_name: string
  public last_name: string
  public prefix_id: number
  public suffix_id: number
  public formal_title: string
  public communication_style_id: number
  public email_greeting_id: number
  public email_greeting_custom: string
  public email_greeting_display: string
  public postal_greeting_id: number
  public postal_greeting_custom: string
  public postal_greeting_display: string
  public addressee_id: number
  public addressee_custom: string
  public addressee_display: string
  public job_title: string
  public gender_id: number
  public birth_date: Date
  public is_deceased: boolean
  public deceased_date: Date
  public household_name: string
  public primary_contact_id: number
  public organization_name: string
  public sic_code: string
  public user_unique_id: string
  public employer_id: number
  public is_deleted: boolean
  public created_date: Date
  public modified_date: Date
  public custom_11: string
  public custom_1: string
  public custom_2: string
  public custom_3: Date
  public address_id: number
  public street_address: string
  public supplemental_address_1: string
  public supplemental_address_2: string
  public supplemental_address_3: string
  public current_employer: string
  public city: string
  public postal_code_suffix: string
  public postal_code: string
  public geo_code_1: string
  public geo_code_2: string
  public state_province_id: number
  public state_province_name: string
  public state_province: string
  public country_id: number
  public country: string
  public worldregion_id: number
  public worldregion: string
  public phone_id: number
  public phone: string
  public phone_type_id: number
  public provider_id: number
  public email_id: number
  public email: string
  public on_hold: boolean
  public im: string
  public im_id: number
  public group: string
  public tag: string
  public birth_date_low: Date
  public birth_date_high: Date
  public deceased_date_low: Date
  public deceased_date_high: Date
}
