export class ContributionRecur {
  public id: number
  public contact_id: number
  public amount: number
  public currency: string
  public frequency_unit: string
  public frequency_interval: number
  public installments: number
  public start_date: Date
  public create_date: Date
  public modified_date: Date
  public cancel_date: Date
  public end_date: Date
  public processor_id: string
  public payment_token_id: number
  public trxn_id: string
  public invoice_id: string
  public contribution_status_id: number
  public is_test: boolean
  public cycle_day: number
  public next_sched_contribution_date: Date
  public failure_count: number
  public failure_retry_date: Date
  public auto_renew: boolean
  public payment_processor_id: number
  public financial_type_id: number
  public payment_instrument_id: number
  public campaign_id: number
  public is_email_receipt: boolean
}
