export class Contribution {
  public financial_type_id: number
  public contribution_page_id: number
  public payment_instrument_id: number
  public receive_date: Date
  public non_deductible_amount: number
  public total_amount: number
  public fee_amount: number
  public net_amount: number
  public trxn_id: string
  public invoice_id: string
  public invoice_number: string
  public currency: string
  public cancel_date: Date
  public cancel_reason: string
  public receipt_date: Date
  public thankyou_date: Date
  public source: string
  public amount_level: string
  public contribution_recur_id: number
  public is_test: boolean
  public is_pay_later: boolean
  public contribution_status_id: number
  public address_id: number
  public check_number: string
  public campaign_id: number
  public creditnote_id: string
  public tax_amount: number
  public revenue_recognition_date: Date
  public custom_6: string
  public custom_5: string
  public id: number
  public contribution_test: boolean
  public contact_id: number
}
