export class CustomField {
  public id: number
  public custom_group_id: number
  public name: string
  public label: string
  public data_type: string
  public html_type: string
  public default_value: string
  public is_required: boolean
  public is_searchable: boolean
  public is_search_range: boolean
  public weight: number
  public help_pre: string
  public help_post: string
  public mask: string
  public attributes: string
  public javascript: string
  public is_active: boolean
  public is_view: boolean
  public options_per_line: number
  public text_length: number
  public start_date_years: number
  public end_date_years: number
  public date_format: string
  public time_format: number
  public note_columns: number
  public note_rows: number
  public column_name: string
  public option_group_id: number
  public filter: string
  public in_selector: boolean
}
