export class Event {
  public id: number
  public title: string
  public summary: string
  public description: string
  public event_type_id: number
  public participant_listing_id: number
  public is_public: boolean
  public start_date: Date
  public end_date: Date
  public is_online_registration: boolean
  public registration_link_text: string
  public registration_start_date: Date
  public registration_end_date: Date
  public max_participants: number
  public event_full_text: string
  public is_monetary: boolean
  public financial_type_id: number
  public payment_processor: string
  public is_map: boolean
  public is_active: boolean
  public fee_label: string
  public is_show_location: boolean
  public loc_block_id: number
  public default_role_id: number
  public intro_text: string
  public footer_text: string
  public confirm_title: string
  public confirm_text: string
  public confirm_footer_text: string
  public is_email_confirm: boolean
  public confirm_email_text: string
  public confirm_from_name: string
  public confirm_from_email: string
  public cc_confirm: string
  public bcc_confirm: string
  public default_fee_id: number
  public default_discount_fee_id: number
  public thankyou_title: string
  public thankyou_text: string
  public thankyou_footer_text: string
  public is_pay_later: boolean
  public pay_later_text: string
  public pay_later_receipt: string
  public is_partial_payment: boolean
  public initial_amount_label: string
  public initial_amount_help_text: string
  public min_initial_amount: number
  public is_multiple_registrations: boolean
  public max_additional_participants: number
  public allow_same_participant_emails: boolean
  public has_waitlist: boolean
  public requires_approval: boolean
  public expiration_time: number
  public allow_selfcancelxfer: boolean
  public selfcancelxfer_time: number
  public waitlist_text: string
  public approval_req_text: string
  public is_template: boolean
  public template_title: string
  public created_id: number
  public created_date: Date
  public currency: string
  public campaign_id: number
  public is_share: boolean
  public is_confirm_enabled: boolean
  public parent_event_id: number
  public slot_label_id: number
  public dedupe_rule_group_id: number
  public is_billing_required: boolean
}
