export class Setting {
  public address_standardization_provider: string
  public address_standardization_userid: string
  public address_standardization_url: string
  public hideCountryMailingLabels: boolean
  public tag_unconfirmed: string
  public petition_contacts: string
  public civicaseRedactActivityEmail: string
  public civicaseAllowMultipleClients: string
  public civicaseNaturalActivityTypeSort: string
  public civicaseActivityRevisions: boolean
  public cvv_backoffice_required: boolean
  public contribution_invoice_settings: string
  public invoicing: number
  public acl_financial_type: number
  public deferred_revenue_enabled: number
  public default_invoice_page: number
  public always_post_to_accounts_receivable: number
  public update_contribution_on_membership_type_change: number
  public contact_view_options: string
  public contact_edit_options: string
  public advanced_search_options: string
  public user_dashboard_options: string
  public address_options: string
  public address_format: string
  public mailing_format: string
  public display_name_format: string
  public sort_name_format: string
  public remote_profile_submissions: boolean
  public allow_alert_autodismissal: boolean
  public editor_id: string
  public contact_ajax_check_similar: string
  public ajaxPopupsEnabled: boolean
  public activity_assignee_notification: string
  public activity_assignee_notification_ics: string
  public contact_autocomplete_options: string
  public contact_reference_options: string
  public contact_smart_group_display: string
  public smart_group_cache_refresh_mode: string
  public installed: boolean
  public max_attachments: number
  public maxFileSize: number
  public contact_undelete: boolean
  public allowPermDeleteFinancial: boolean
  public securityAlert: boolean
  public doNotAttachPDFReceipt: boolean
  public recordGeneratedLetters: string
  public wkhtmltopdfPath: string
  public recaptchaOptions: string
  public recaptchaPublicKey: string
  public recaptchaPrivateKey: string
  public checksum_timeout: number
  public blogUrl: string
  public communityMessagesUrl: string
  public gettingStartedUrl: string
  public resCacheCode: string
  public verifySSL: boolean
  public enableSSL: boolean
  public wpBasePage: string
  public secondDegRelPermissions: boolean
  public enable_components: string
  public disable_core_css: boolean
  public empoweredBy: boolean
  public logging_no_trigger_permission: boolean
  public logging: boolean
  public logging_uniqueid_date: Date
  public logging_all_tables_uniquid: boolean
  public userFrameworkUsersTableName: string
  public wpLoadPhp: string
  public secure_cache_timeout_minutes: number
  public site_id: string
  public recentItemsMaxCount: number
  public recentItemsProviders: string
  public dedupe_default_limit: number
  public syncCMSEmail: boolean
  public preserve_activity_tab_filter: string
  public do_not_notify_assignees_for: string
  public assetCache: string
  public userFrameworkLogging: boolean
  public debug_enabled: boolean
  public backtrace: boolean
  public environment: string
  public fatalErrorHandler: string
  public uploadDir: string
  public imageUploadDir: string
  public customFileUploadDir: string
  public customTemplateDir: string
  public customPHPPathDir: string
  public extensionsDir: string
  public enable_cart: boolean
  public show_events: number
  public ext_repo_url: string
  public customTranslateFunction: string
  public monetaryThousandSeparator: string
  public monetaryDecimalPoint: string
  public moneyformat: string
  public moneyvalueformat: string
  public defaultCurrency: string
  public defaultContactCountry: string
  public defaultContactStateProvince: number
  public countryLimit: string
  public provinceLimit: string
  public inheritLocale: boolean
  public dateformatDatetime: string
  public dateformatFull: string
  public dateformatPartial: string
  public dateformatTime: string
  public dateformatYear: string
  public dateformatFinancialBatch: string
  public dateformatshortdate: string
  public dateInputFormat: string
  public fieldSeparator: string
  public fiscalYearStart: string
  public languageLimit: string
  public lcMessages: string
  public legacyEncoding: string
  public timeInputFormat: string
  public weekBegins: string
  public contact_default_language: string
  public profile_double_optin: number
  public track_civimail_replies: number
  public civimail_workflow: number
  public civimail_server_wide_lock: number
  public replyTo: boolean
  public mailing_backend: string
  public profile_add_to_group_double_optin: number
  public disable_mandatory_tokens_check: number
  public dedupe_email_default: number
  public hash_mailing_url: number
  public civimail_multiple_bulk_emails: number
  public include_message_id: number
  public mailerBatchLimit: number
  public mailerJobSize: number
  public mailerJobsMax: number
  public mailThrottleTime: number
  public verpSeparator: string
  public write_activity_record: boolean
  public simple_mail_limit: number
  public auto_recipient_rebuild: boolean
  public allow_mail_from_logged_in_contact: boolean
  public geoAPIKey: string
  public geoProvider: string
  public mapAPIKey: string
  public mapProvider: string
  public default_renewal_contribution_page: number
  public is_enabled: number
  public domain_group_id: number
  public event_price_set_domain_id: number
  public uniq_email_per_site: number
  public search_autocomplete_count: number
  public enable_innodb_fts: boolean
  public fts_query_mode: string
  public includeOrderByClause: boolean
  public includeWildCardInName: boolean
  public includeEmailInName: boolean
  public includeNickNameInName: boolean
  public includeAlphabeticalPager: boolean
  public smartGroupCacheTimeout: number
  public defaultSearchProfileID: number
  public searchPrimaryDetailsOnly: boolean
  public userFrameworkResourceURL: string
  public imageUploadURL: string
  public customCSSURL: string
  public extensionsURL: string
  public slider_widget_fields: string
  public volunteer_project_default_profiles: string
  public volunteer_project_default_campaign: number
  public volunteer_project_default_locblock: number
  public volunteer_project_default_is_active: number
  public volunteer_project_default_contacts: string
  public volunteer_general_campaign_filter_type: string
  public volunteer_general_campaign_filter_list: string
  public volunteer_general_project_settings_help_text: string
}
