export class UFGroup {
  public id: number
  public is_active: boolean
  public group_type: string
  public title: string
  public frontend_title: string
  public description: string
  public help_pre: string
  public help_post: string
  public limit_listings_group_id: number
  public post_URL: string
  public add_to_group_id: number
  public add_captcha: boolean
  public is_map: boolean
  public is_edit_link: boolean
  public is_uf_link: boolean
  public is_update_dupe: boolean
  public cancel_URL: string
  public is_cms_user: boolean
  public notify: string
  public is_reserved: boolean
  public name: string
  public created_id: number
  public created_date: Date
  public is_proximity_search: boolean
  public cancel_button_text: string
  public submit_button_text: string
  public add_cancel_button: boolean
}
